//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PfizerEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster
    {
        public decimal PKID { get; set; }
        public string EmpCode { get; set; }
        public Nullable<decimal> TitleFKID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string ShortName { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Address { get; set; }
        public string Street { get; set; }
        public string Area { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNo { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string HQ { get; set; }
        public Nullable<int> MartialStatusFKID { get; set; }
        public Nullable<int> DesignationFKID { get; set; }
        public string OldEmployeeCode { get; set; }
        public string TempAddress1 { get; set; }
        public string TempAddress2 { get; set; }
        public string TempCity { get; set; }
        public string TempArea { get; set; }
        public string TempZipCode { get; set; }
        public Nullable<System.DateTime> LastAddresUpdateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public string PhoneSTDCode { get; set; }
        public string PhoneISDCode { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
