//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PfizerEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQS1View
    {
        public decimal PKID { get; set; }
        public decimal CategoryFKID { get; set; }
        public string GenName { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string IsActive { get; set; }
    }
}
