//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PfizerEntity
{
    using System;
    
    public partial class GetHospitalMaster_PSO_Result1
    {
        public int HospitalID { get; set; }
        public string NameofHospital { get; set; }
        public string HotelAddress { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string CityCode { get; set; }
        public string Area { get; set; }
        public Nullable<decimal> ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
    }
}
