//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PfizerEntity
{
    using System;
    
    public partial class usp_Get_CampTypeMaster_Result2
    {
        public decimal PKID { get; set; }
        public string TableName { get; set; }
        public string GenCode { get; set; }
        public string GenName { get; set; }
        public decimal GenFKID { get; set; }
        public string IsActive { get; set; }
    }
}
